Name:           ros-indigo-romeo-sensors
Version:        0.0.9
Release:        0%{?dist}
Summary:        ROS romeo_sensors package

Group:          Development/Libraries
License:        BSD
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-indigo-nao-sensors
Requires:       ros-indigo-roscpp
Requires:       ros-indigo-rospy
BuildRequires:  ros-indigo-catkin
BuildRequires:  ros-indigo-nao-sensors
BuildRequires:  ros-indigo-roscpp
BuildRequires:  ros-indigo-rospy

%description
The romeo_sensors package

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
mkdir -p build && cd build
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/indigo" \
        -DCMAKE_PREFIX_PATH="/opt/ros/indigo" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
cd build
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/indigo

%changelog
* Thu Sep 25 2014 Ha Dang <hris2003@gmail.com> - 0.0.9-0
- Autogenerated by Bloom

* Mon Sep 22 2014 Ha Dang <hris2003@gmail.com> - 0.0.8-0
- Autogenerated by Bloom

* Mon Sep 22 2014 Ha Dang <hris2003@gmail.com> - 0.0.7-0
- Autogenerated by Bloom

* Fri Sep 19 2014 Ha Dang <hris2003@gmail.com> - 0.0.6-0
- Autogenerated by Bloom

* Thu Sep 18 2014 Ha Dang <hris2003@gmail.com> - 0.0.5-0
- Autogenerated by Bloom

